### PR TITLE
Adding skip option to the plugin

### PR DESCRIPTION
**Pull request by kutsal**
Recently needed the ability to skip execution of this plugin. This PR adds that option.

### CODE REVIEW

**Comment by RobWin** [comment]
Thx for your PR. Could you please revert your changes in the `pom.xml`.

If you use and like Swagger2Markup, we would love to get your GitHub Star.

**Comment by kutsal** [comment]
@RobWin done. Thank you.

**Comment by patrickbray** [comment]
I am running into the same issue is there anything stopping merging this and releasing a new version of this plugin?

**Comment by RobWin** [comment]
Would you like to create a new PR and rebase on the current master branch?

**Comment by venkateshshukla** [comment]
This is really needed. Can this be merged as soon as possible?

**Comment by RobWin** [comment]
Can't you use Maven Profiles in the meantime?

**Comment by nikit-cpp** [comment]
+1

**Comment by roltean** [comment]
Robert, would you please merge this? I would be a huge help to me. It's the only missing piece in the docs generation puzzle. asciidoctor-maven-plugin also has the skip option and it works.
Thank you!

**Comment by RobWin** [comment]
Its already merged but not released.

**Comment by roltean** [comment]
Awesome! Could you release it anytime soon?

**Comment by roltean** [comment]
My bad. Placed the <skip> tag in the wrong place. Everything checks out. Could please release as soon as possible?

Thank you!

**Comment by RobWin** [comment]
Done

**Comment by roltean** [comment]
Looks good. 👍🏻
Much appreciated!

**Pull request closed without merging**
