### PR TITLE
Allow `swaggerInput` to be a local directory

### LINKED ISSUE #41: Support setting directories for property 'swaggerInput'
It's rather limiting that [`swaggerInput`](https://swagger2markup.github.io/swagger2markup/1.3.1/#_configuration_3) cannot be the path to a folder that contains Swagger files. True, the plugin can be configured multiple times as a workaround but that's really ugly.

Ideally I could set a directory for `swaggerInput` and have the plugin deep-scan it for Swagger files.

### PR DESCRIPTION
**Pull request by marcelstoer**
Fixes #41

### CODE REVIEW

**Comment by RobWin** [comment]
Thx, Would you also like to implement the similar solution in our gradle plugin?

**Comment by marcelstoer** [comment]
Merge this, release it and I'll see what I can do. Deal 😜 ? Would be a good opportunity for me to enter the Groovy world.

**Comment by marcelstoer** [comment]
Thanks, could you please also cut another release so that we don't have to host a patched version in our internal Nexus repo?

**Comment by RobWin** [comment]
Sure I hope I have some time on Monday.

**Pull request merged**
